apiVersion: apps/v1
kind: Deployment
metadata:
  name: autotops-demo
  labels:
    app: autotops-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: autotops-demo

  template:
    metadata:
      labels:
        app: autotops-demo

    spec:
      containers:
        - name: autotops-demo
          image: autotops-demo:0.1

          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"